// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: models/Client.proto

#include "models/Client.pb.h"
#include "models/Client.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace TestApiGrpc {
namespace Protos {
namespace models {

} // namespace TestApiGrpc
} // namespace Protos
} // namespace models

