// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/Invoices.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_models_2fInvoices_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_models_2fInvoices_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "models/Client.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_models_2fInvoices_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_models_2fInvoices_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_models_2fInvoices_2eproto;
namespace TestApiGrpc {
namespace Protos {
namespace models {
class Invoices;
struct InvoicesDefaultTypeInternal;
extern InvoicesDefaultTypeInternal _Invoices_default_instance_;
}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc
PROTOBUF_NAMESPACE_OPEN
template<> ::TestApiGrpc::Protos::models::Invoices* Arena::CreateMaybeMessage<::TestApiGrpc::Protos::models::Invoices>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace TestApiGrpc {
namespace Protos {
namespace models {

// ===================================================================

class Invoices final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TestApiGrpc.Protos.models.Invoices) */ {
 public:
  inline Invoices() : Invoices(nullptr) {}
  ~Invoices() override;
  explicit PROTOBUF_CONSTEXPR Invoices(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Invoices(const Invoices& from);
  Invoices(Invoices&& from) noexcept
    : Invoices() {
    *this = ::std::move(from);
  }

  inline Invoices& operator=(const Invoices& from) {
    CopyFrom(from);
    return *this;
  }
  inline Invoices& operator=(Invoices&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Invoices& default_instance() {
    return *internal_default_instance();
  }
  static inline const Invoices* internal_default_instance() {
    return reinterpret_cast<const Invoices*>(
               &_Invoices_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Invoices& a, Invoices& b) {
    a.Swap(&b);
  }
  inline void Swap(Invoices* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Invoices* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Invoices* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Invoices>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Invoices& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Invoices& from) {
    Invoices::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Invoices* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TestApiGrpc.Protos.models.Invoices";
  }
  protected:
  explicit Invoices(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInvoiceDetailsFieldNumber = 5,
    kRefClientFieldNumber = 1,
    kDiscountProductFieldNumber = 2,
    kAmountProductFieldNumber = 3,
    kTotalPayFieldNumber = 4,
  };
  // repeated string invoice_details = 5;
  int invoice_details_size() const;
  private:
  int _internal_invoice_details_size() const;
  public:
  void clear_invoice_details();
  const std::string& invoice_details(int index) const;
  std::string* mutable_invoice_details(int index);
  void set_invoice_details(int index, const std::string& value);
  void set_invoice_details(int index, std::string&& value);
  void set_invoice_details(int index, const char* value);
  void set_invoice_details(int index, const char* value, size_t size);
  std::string* add_invoice_details();
  void add_invoice_details(const std::string& value);
  void add_invoice_details(std::string&& value);
  void add_invoice_details(const char* value);
  void add_invoice_details(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& invoice_details() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_invoice_details();
  private:
  const std::string& _internal_invoice_details(int index) const;
  std::string* _internal_add_invoice_details();
  public:

  // .TestApiGrpc.Protos.models.Client ref_client = 1;
  bool has_ref_client() const;
  private:
  bool _internal_has_ref_client() const;
  public:
  void clear_ref_client();
  const ::TestApiGrpc::Protos::models::Client& ref_client() const;
  PROTOBUF_NODISCARD ::TestApiGrpc::Protos::models::Client* release_ref_client();
  ::TestApiGrpc::Protos::models::Client* mutable_ref_client();
  void set_allocated_ref_client(::TestApiGrpc::Protos::models::Client* ref_client);
  private:
  const ::TestApiGrpc::Protos::models::Client& _internal_ref_client() const;
  ::TestApiGrpc::Protos::models::Client* _internal_mutable_ref_client();
  public:
  void unsafe_arena_set_allocated_ref_client(
      ::TestApiGrpc::Protos::models::Client* ref_client);
  ::TestApiGrpc::Protos::models::Client* unsafe_arena_release_ref_client();

  // int32 discount_product = 2;
  void clear_discount_product();
  int32_t discount_product() const;
  void set_discount_product(int32_t value);
  private:
  int32_t _internal_discount_product() const;
  void _internal_set_discount_product(int32_t value);
  public:

  // int32 amount_product = 3;
  void clear_amount_product();
  int32_t amount_product() const;
  void set_amount_product(int32_t value);
  private:
  int32_t _internal_amount_product() const;
  void _internal_set_amount_product(int32_t value);
  public:

  // int32 total_pay = 4;
  void clear_total_pay();
  int32_t total_pay() const;
  void set_total_pay(int32_t value);
  private:
  int32_t _internal_total_pay() const;
  void _internal_set_total_pay(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:TestApiGrpc.Protos.models.Invoices)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> invoice_details_;
    ::TestApiGrpc::Protos::models::Client* ref_client_;
    int32_t discount_product_;
    int32_t amount_product_;
    int32_t total_pay_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_models_2fInvoices_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Invoices

// .TestApiGrpc.Protos.models.Client ref_client = 1;
inline bool Invoices::_internal_has_ref_client() const {
  return this != internal_default_instance() && _impl_.ref_client_ != nullptr;
}
inline bool Invoices::has_ref_client() const {
  return _internal_has_ref_client();
}
inline const ::TestApiGrpc::Protos::models::Client& Invoices::_internal_ref_client() const {
  const ::TestApiGrpc::Protos::models::Client* p = _impl_.ref_client_;
  return p != nullptr ? *p : reinterpret_cast<const ::TestApiGrpc::Protos::models::Client&>(
      ::TestApiGrpc::Protos::models::_Client_default_instance_);
}
inline const ::TestApiGrpc::Protos::models::Client& Invoices::ref_client() const {
  // @@protoc_insertion_point(field_get:TestApiGrpc.Protos.models.Invoices.ref_client)
  return _internal_ref_client();
}
inline void Invoices::unsafe_arena_set_allocated_ref_client(
    ::TestApiGrpc::Protos::models::Client* ref_client) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ref_client_);
  }
  _impl_.ref_client_ = ref_client;
  if (ref_client) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TestApiGrpc.Protos.models.Invoices.ref_client)
}
inline ::TestApiGrpc::Protos::models::Client* Invoices::release_ref_client() {
  
  ::TestApiGrpc::Protos::models::Client* temp = _impl_.ref_client_;
  _impl_.ref_client_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::TestApiGrpc::Protos::models::Client* Invoices::unsafe_arena_release_ref_client() {
  // @@protoc_insertion_point(field_release:TestApiGrpc.Protos.models.Invoices.ref_client)
  
  ::TestApiGrpc::Protos::models::Client* temp = _impl_.ref_client_;
  _impl_.ref_client_ = nullptr;
  return temp;
}
inline ::TestApiGrpc::Protos::models::Client* Invoices::_internal_mutable_ref_client() {
  
  if (_impl_.ref_client_ == nullptr) {
    auto* p = CreateMaybeMessage<::TestApiGrpc::Protos::models::Client>(GetArenaForAllocation());
    _impl_.ref_client_ = p;
  }
  return _impl_.ref_client_;
}
inline ::TestApiGrpc::Protos::models::Client* Invoices::mutable_ref_client() {
  ::TestApiGrpc::Protos::models::Client* _msg = _internal_mutable_ref_client();
  // @@protoc_insertion_point(field_mutable:TestApiGrpc.Protos.models.Invoices.ref_client)
  return _msg;
}
inline void Invoices::set_allocated_ref_client(::TestApiGrpc::Protos::models::Client* ref_client) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ref_client_);
  }
  if (ref_client) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ref_client));
    if (message_arena != submessage_arena) {
      ref_client = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ref_client, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.ref_client_ = ref_client;
  // @@protoc_insertion_point(field_set_allocated:TestApiGrpc.Protos.models.Invoices.ref_client)
}

// int32 discount_product = 2;
inline void Invoices::clear_discount_product() {
  _impl_.discount_product_ = 0;
}
inline int32_t Invoices::_internal_discount_product() const {
  return _impl_.discount_product_;
}
inline int32_t Invoices::discount_product() const {
  // @@protoc_insertion_point(field_get:TestApiGrpc.Protos.models.Invoices.discount_product)
  return _internal_discount_product();
}
inline void Invoices::_internal_set_discount_product(int32_t value) {
  
  _impl_.discount_product_ = value;
}
inline void Invoices::set_discount_product(int32_t value) {
  _internal_set_discount_product(value);
  // @@protoc_insertion_point(field_set:TestApiGrpc.Protos.models.Invoices.discount_product)
}

// int32 amount_product = 3;
inline void Invoices::clear_amount_product() {
  _impl_.amount_product_ = 0;
}
inline int32_t Invoices::_internal_amount_product() const {
  return _impl_.amount_product_;
}
inline int32_t Invoices::amount_product() const {
  // @@protoc_insertion_point(field_get:TestApiGrpc.Protos.models.Invoices.amount_product)
  return _internal_amount_product();
}
inline void Invoices::_internal_set_amount_product(int32_t value) {
  
  _impl_.amount_product_ = value;
}
inline void Invoices::set_amount_product(int32_t value) {
  _internal_set_amount_product(value);
  // @@protoc_insertion_point(field_set:TestApiGrpc.Protos.models.Invoices.amount_product)
}

// int32 total_pay = 4;
inline void Invoices::clear_total_pay() {
  _impl_.total_pay_ = 0;
}
inline int32_t Invoices::_internal_total_pay() const {
  return _impl_.total_pay_;
}
inline int32_t Invoices::total_pay() const {
  // @@protoc_insertion_point(field_get:TestApiGrpc.Protos.models.Invoices.total_pay)
  return _internal_total_pay();
}
inline void Invoices::_internal_set_total_pay(int32_t value) {
  
  _impl_.total_pay_ = value;
}
inline void Invoices::set_total_pay(int32_t value) {
  _internal_set_total_pay(value);
  // @@protoc_insertion_point(field_set:TestApiGrpc.Protos.models.Invoices.total_pay)
}

// repeated string invoice_details = 5;
inline int Invoices::_internal_invoice_details_size() const {
  return _impl_.invoice_details_.size();
}
inline int Invoices::invoice_details_size() const {
  return _internal_invoice_details_size();
}
inline void Invoices::clear_invoice_details() {
  _impl_.invoice_details_.Clear();
}
inline std::string* Invoices::add_invoice_details() {
  std::string* _s = _internal_add_invoice_details();
  // @@protoc_insertion_point(field_add_mutable:TestApiGrpc.Protos.models.Invoices.invoice_details)
  return _s;
}
inline const std::string& Invoices::_internal_invoice_details(int index) const {
  return _impl_.invoice_details_.Get(index);
}
inline const std::string& Invoices::invoice_details(int index) const {
  // @@protoc_insertion_point(field_get:TestApiGrpc.Protos.models.Invoices.invoice_details)
  return _internal_invoice_details(index);
}
inline std::string* Invoices::mutable_invoice_details(int index) {
  // @@protoc_insertion_point(field_mutable:TestApiGrpc.Protos.models.Invoices.invoice_details)
  return _impl_.invoice_details_.Mutable(index);
}
inline void Invoices::set_invoice_details(int index, const std::string& value) {
  _impl_.invoice_details_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline void Invoices::set_invoice_details(int index, std::string&& value) {
  _impl_.invoice_details_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline void Invoices::set_invoice_details(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.invoice_details_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline void Invoices::set_invoice_details(int index, const char* value, size_t size) {
  _impl_.invoice_details_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline std::string* Invoices::_internal_add_invoice_details() {
  return _impl_.invoice_details_.Add();
}
inline void Invoices::add_invoice_details(const std::string& value) {
  _impl_.invoice_details_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline void Invoices::add_invoice_details(std::string&& value) {
  _impl_.invoice_details_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline void Invoices::add_invoice_details(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.invoice_details_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline void Invoices::add_invoice_details(const char* value, size_t size) {
  _impl_.invoice_details_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:TestApiGrpc.Protos.models.Invoices.invoice_details)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Invoices::invoice_details() const {
  // @@protoc_insertion_point(field_list:TestApiGrpc.Protos.models.Invoices.invoice_details)
  return _impl_.invoice_details_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Invoices::mutable_invoice_details() {
  // @@protoc_insertion_point(field_mutable_list:TestApiGrpc.Protos.models.Invoices.invoice_details)
  return &_impl_.invoice_details_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_models_2fInvoices_2eproto
