// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/Invoices.proto

#include "models/Invoices.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace TestApiGrpc {
namespace Protos {
namespace models {
PROTOBUF_CONSTEXPR Invoices::Invoices(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.invoice_details_)*/{}
  , /*decltype(_impl_.ref_client_)*/nullptr
  , /*decltype(_impl_.discount_product_)*/0
  , /*decltype(_impl_.amount_product_)*/0
  , /*decltype(_impl_.total_pay_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InvoicesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvoicesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvoicesDefaultTypeInternal() {}
  union {
    Invoices _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvoicesDefaultTypeInternal _Invoices_default_instance_;
}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc
static ::_pb::Metadata file_level_metadata_models_2fInvoices_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_models_2fInvoices_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_models_2fInvoices_2eproto = nullptr;

const uint32_t TableStruct_models_2fInvoices_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::Invoices, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::Invoices, _impl_.ref_client_),
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::Invoices, _impl_.discount_product_),
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::Invoices, _impl_.amount_product_),
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::Invoices, _impl_.total_pay_),
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::Invoices, _impl_.invoice_details_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::TestApiGrpc::Protos::models::Invoices)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::TestApiGrpc::Protos::models::_Invoices_default_instance_._instance,
};

const char descriptor_table_protodef_models_2fInvoices_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025models/Invoices.proto\022\031TestApiGrpc.Pro"
  "tos.models\032\023models/Client.proto\"\237\001\n\010Invo"
  "ices\0225\n\nref_client\030\001 \001(\0132!.TestApiGrpc.P"
  "rotos.models.Client\022\030\n\020discount_product\030"
  "\002 \001(\005\022\026\n\016amount_product\030\003 \001(\005\022\021\n\ttotal_p"
  "ay\030\004 \001(\005\022\027\n\017invoice_details\030\005 \003(\tb\006proto"
  "3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_models_2fInvoices_2eproto_deps[1] = {
  &::descriptor_table_models_2fClient_2eproto,
};
static ::_pbi::once_flag descriptor_table_models_2fInvoices_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_models_2fInvoices_2eproto = {
    false, false, 241, descriptor_table_protodef_models_2fInvoices_2eproto,
    "models/Invoices.proto",
    &descriptor_table_models_2fInvoices_2eproto_once, descriptor_table_models_2fInvoices_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_models_2fInvoices_2eproto::offsets,
    file_level_metadata_models_2fInvoices_2eproto, file_level_enum_descriptors_models_2fInvoices_2eproto,
    file_level_service_descriptors_models_2fInvoices_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_models_2fInvoices_2eproto_getter() {
  return &descriptor_table_models_2fInvoices_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_models_2fInvoices_2eproto(&descriptor_table_models_2fInvoices_2eproto);
namespace TestApiGrpc {
namespace Protos {
namespace models {

// ===================================================================

class Invoices::_Internal {
 public:
  static const ::TestApiGrpc::Protos::models::Client& ref_client(const Invoices* msg);
};

const ::TestApiGrpc::Protos::models::Client&
Invoices::_Internal::ref_client(const Invoices* msg) {
  return *msg->_impl_.ref_client_;
}
void Invoices::clear_ref_client() {
  if (GetArenaForAllocation() == nullptr && _impl_.ref_client_ != nullptr) {
    delete _impl_.ref_client_;
  }
  _impl_.ref_client_ = nullptr;
}
Invoices::Invoices(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TestApiGrpc.Protos.models.Invoices)
}
Invoices::Invoices(const Invoices& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Invoices* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_details_){from._impl_.invoice_details_}
    , decltype(_impl_.ref_client_){nullptr}
    , decltype(_impl_.discount_product_){}
    , decltype(_impl_.amount_product_){}
    , decltype(_impl_.total_pay_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_ref_client()) {
    _this->_impl_.ref_client_ = new ::TestApiGrpc::Protos::models::Client(*from._impl_.ref_client_);
  }
  ::memcpy(&_impl_.discount_product_, &from._impl_.discount_product_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.total_pay_) -
    reinterpret_cast<char*>(&_impl_.discount_product_)) + sizeof(_impl_.total_pay_));
  // @@protoc_insertion_point(copy_constructor:TestApiGrpc.Protos.models.Invoices)
}

inline void Invoices::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_details_){arena}
    , decltype(_impl_.ref_client_){nullptr}
    , decltype(_impl_.discount_product_){0}
    , decltype(_impl_.amount_product_){0}
    , decltype(_impl_.total_pay_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Invoices::~Invoices() {
  // @@protoc_insertion_point(destructor:TestApiGrpc.Protos.models.Invoices)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Invoices::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.invoice_details_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.ref_client_;
}

void Invoices::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Invoices::Clear() {
// @@protoc_insertion_point(message_clear_start:TestApiGrpc.Protos.models.Invoices)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.invoice_details_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.ref_client_ != nullptr) {
    delete _impl_.ref_client_;
  }
  _impl_.ref_client_ = nullptr;
  ::memset(&_impl_.discount_product_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.total_pay_) -
      reinterpret_cast<char*>(&_impl_.discount_product_)) + sizeof(_impl_.total_pay_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Invoices::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .TestApiGrpc.Protos.models.Client ref_client = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_ref_client(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 discount_product = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.discount_product_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 amount_product = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.amount_product_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 total_pay = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.total_pay_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string invoice_details = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_invoice_details();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "TestApiGrpc.Protos.models.Invoices.invoice_details"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Invoices::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TestApiGrpc.Protos.models.Invoices)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .TestApiGrpc.Protos.models.Client ref_client = 1;
  if (this->_internal_has_ref_client()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::ref_client(this),
        _Internal::ref_client(this).GetCachedSize(), target, stream);
  }

  // int32 discount_product = 2;
  if (this->_internal_discount_product() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_discount_product(), target);
  }

  // int32 amount_product = 3;
  if (this->_internal_amount_product() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_amount_product(), target);
  }

  // int32 total_pay = 4;
  if (this->_internal_total_pay() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_total_pay(), target);
  }

  // repeated string invoice_details = 5;
  for (int i = 0, n = this->_internal_invoice_details_size(); i < n; i++) {
    const auto& s = this->_internal_invoice_details(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TestApiGrpc.Protos.models.Invoices.invoice_details");
    target = stream->WriteString(5, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TestApiGrpc.Protos.models.Invoices)
  return target;
}

size_t Invoices::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TestApiGrpc.Protos.models.Invoices)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string invoice_details = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.invoice_details_.size());
  for (int i = 0, n = _impl_.invoice_details_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.invoice_details_.Get(i));
  }

  // .TestApiGrpc.Protos.models.Client ref_client = 1;
  if (this->_internal_has_ref_client()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ref_client_);
  }

  // int32 discount_product = 2;
  if (this->_internal_discount_product() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_discount_product());
  }

  // int32 amount_product = 3;
  if (this->_internal_amount_product() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_amount_product());
  }

  // int32 total_pay = 4;
  if (this->_internal_total_pay() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_total_pay());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Invoices::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Invoices::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Invoices::GetClassData() const { return &_class_data_; }


void Invoices::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Invoices*>(&to_msg);
  auto& from = static_cast<const Invoices&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestApiGrpc.Protos.models.Invoices)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.invoice_details_.MergeFrom(from._impl_.invoice_details_);
  if (from._internal_has_ref_client()) {
    _this->_internal_mutable_ref_client()->::TestApiGrpc::Protos::models::Client::MergeFrom(
        from._internal_ref_client());
  }
  if (from._internal_discount_product() != 0) {
    _this->_internal_set_discount_product(from._internal_discount_product());
  }
  if (from._internal_amount_product() != 0) {
    _this->_internal_set_amount_product(from._internal_amount_product());
  }
  if (from._internal_total_pay() != 0) {
    _this->_internal_set_total_pay(from._internal_total_pay());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Invoices::CopyFrom(const Invoices& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestApiGrpc.Protos.models.Invoices)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Invoices::IsInitialized() const {
  return true;
}

void Invoices::InternalSwap(Invoices* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.invoice_details_.InternalSwap(&other->_impl_.invoice_details_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Invoices, _impl_.total_pay_)
      + sizeof(Invoices::_impl_.total_pay_)
      - PROTOBUF_FIELD_OFFSET(Invoices, _impl_.ref_client_)>(
          reinterpret_cast<char*>(&_impl_.ref_client_),
          reinterpret_cast<char*>(&other->_impl_.ref_client_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Invoices::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_models_2fInvoices_2eproto_getter, &descriptor_table_models_2fInvoices_2eproto_once,
      file_level_metadata_models_2fInvoices_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TestApiGrpc::Protos::models::Invoices*
Arena::CreateMaybeMessage< ::TestApiGrpc::Protos::models::Invoices >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TestApiGrpc::Protos::models::Invoices >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
