// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model_services/InvoicesService.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_model_5fservices_2fInvoicesService_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_model_5fservices_2fInvoicesService_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "models/Invoices.pb.h"
#include "models/ServiceStatus.pb.h"
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_model_5fservices_2fInvoicesService_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_model_5fservices_2fInvoicesService_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_model_5fservices_2fInvoicesService_2eproto;
namespace TestApiGrpc {
namespace Protos {
namespace models {
class ListInvoicesResponse;
struct ListInvoicesResponseDefaultTypeInternal;
extern ListInvoicesResponseDefaultTypeInternal _ListInvoicesResponse_default_instance_;
}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc
PROTOBUF_NAMESPACE_OPEN
template<> ::TestApiGrpc::Protos::models::ListInvoicesResponse* Arena::CreateMaybeMessage<::TestApiGrpc::Protos::models::ListInvoicesResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace TestApiGrpc {
namespace Protos {
namespace models {

// ===================================================================

class ListInvoicesResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TestApiGrpc.Protos.models.ListInvoicesResponse) */ {
 public:
  inline ListInvoicesResponse() : ListInvoicesResponse(nullptr) {}
  ~ListInvoicesResponse() override;
  explicit PROTOBUF_CONSTEXPR ListInvoicesResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ListInvoicesResponse(const ListInvoicesResponse& from);
  ListInvoicesResponse(ListInvoicesResponse&& from) noexcept
    : ListInvoicesResponse() {
    *this = ::std::move(from);
  }

  inline ListInvoicesResponse& operator=(const ListInvoicesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListInvoicesResponse& operator=(ListInvoicesResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListInvoicesResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListInvoicesResponse* internal_default_instance() {
    return reinterpret_cast<const ListInvoicesResponse*>(
               &_ListInvoicesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ListInvoicesResponse& a, ListInvoicesResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ListInvoicesResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListInvoicesResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListInvoicesResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ListInvoicesResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ListInvoicesResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ListInvoicesResponse& from) {
    ListInvoicesResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListInvoicesResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TestApiGrpc.Protos.models.ListInvoicesResponse";
  }
  protected:
  explicit ListInvoicesResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInvoiceFieldNumber = 1,
  };
  // repeated .TestApiGrpc.Protos.models.Invoices invoice = 1;
  int invoice_size() const;
  private:
  int _internal_invoice_size() const;
  public:
  void clear_invoice();
  ::TestApiGrpc::Protos::models::Invoices* mutable_invoice(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TestApiGrpc::Protos::models::Invoices >*
      mutable_invoice();
  private:
  const ::TestApiGrpc::Protos::models::Invoices& _internal_invoice(int index) const;
  ::TestApiGrpc::Protos::models::Invoices* _internal_add_invoice();
  public:
  const ::TestApiGrpc::Protos::models::Invoices& invoice(int index) const;
  ::TestApiGrpc::Protos::models::Invoices* add_invoice();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TestApiGrpc::Protos::models::Invoices >&
      invoice() const;

  // @@protoc_insertion_point(class_scope:TestApiGrpc.Protos.models.ListInvoicesResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TestApiGrpc::Protos::models::Invoices > invoice_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_model_5fservices_2fInvoicesService_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ListInvoicesResponse

// repeated .TestApiGrpc.Protos.models.Invoices invoice = 1;
inline int ListInvoicesResponse::_internal_invoice_size() const {
  return _impl_.invoice_.size();
}
inline int ListInvoicesResponse::invoice_size() const {
  return _internal_invoice_size();
}
inline ::TestApiGrpc::Protos::models::Invoices* ListInvoicesResponse::mutable_invoice(int index) {
  // @@protoc_insertion_point(field_mutable:TestApiGrpc.Protos.models.ListInvoicesResponse.invoice)
  return _impl_.invoice_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TestApiGrpc::Protos::models::Invoices >*
ListInvoicesResponse::mutable_invoice() {
  // @@protoc_insertion_point(field_mutable_list:TestApiGrpc.Protos.models.ListInvoicesResponse.invoice)
  return &_impl_.invoice_;
}
inline const ::TestApiGrpc::Protos::models::Invoices& ListInvoicesResponse::_internal_invoice(int index) const {
  return _impl_.invoice_.Get(index);
}
inline const ::TestApiGrpc::Protos::models::Invoices& ListInvoicesResponse::invoice(int index) const {
  // @@protoc_insertion_point(field_get:TestApiGrpc.Protos.models.ListInvoicesResponse.invoice)
  return _internal_invoice(index);
}
inline ::TestApiGrpc::Protos::models::Invoices* ListInvoicesResponse::_internal_add_invoice() {
  return _impl_.invoice_.Add();
}
inline ::TestApiGrpc::Protos::models::Invoices* ListInvoicesResponse::add_invoice() {
  ::TestApiGrpc::Protos::models::Invoices* _add = _internal_add_invoice();
  // @@protoc_insertion_point(field_add:TestApiGrpc.Protos.models.ListInvoicesResponse.invoice)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TestApiGrpc::Protos::models::Invoices >&
ListInvoicesResponse::invoice() const {
  // @@protoc_insertion_point(field_list:TestApiGrpc.Protos.models.ListInvoicesResponse.invoice)
  return _impl_.invoice_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_model_5fservices_2fInvoicesService_2eproto
