// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: model_services/InvoicesService.proto
// Original file comments:
// InvoicesService.proto
#ifndef GRPC_model_5fservices_2fInvoicesService_2eproto__INCLUDED
#define GRPC_model_5fservices_2fInvoicesService_2eproto__INCLUDED

#include "model_services/InvoicesService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace TestApiGrpc {
namespace Protos {
namespace models {

// Servicio InvoicesService.
class InvoicesService final {
 public:
  static constexpr char const* service_full_name() {
    return "TestApiGrpc.Protos.models.InvoicesService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::TestApiGrpc::Protos::models::ServiceStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ServiceStatus>> AsyncCreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ServiceStatus>>(AsyncCreateInvoicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ServiceStatus>> PrepareAsyncCreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ServiceStatus>>(PrepareAsyncCreateInvoicesRaw(context, request, cq));
    }
    virtual ::grpc::Status ListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ListInvoicesResponse>> AsyncListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ListInvoicesResponse>>(AsyncListInvoicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ListInvoicesResponse>> PrepareAsyncListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ListInvoicesResponse>>(PrepareAsyncListInvoicesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices* request, ::TestApiGrpc::Protos::models::ServiceStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices* request, ::TestApiGrpc::Protos::models::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ServiceStatus>* AsyncCreateInvoicesRaw(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ServiceStatus>* PrepareAsyncCreateInvoicesRaw(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ListInvoicesResponse>* AsyncListInvoicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TestApiGrpc::Protos::models::ListInvoicesResponse>* PrepareAsyncListInvoicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::TestApiGrpc::Protos::models::ServiceStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ServiceStatus>> AsyncCreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ServiceStatus>>(AsyncCreateInvoicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ServiceStatus>> PrepareAsyncCreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ServiceStatus>>(PrepareAsyncCreateInvoicesRaw(context, request, cq));
    }
    ::grpc::Status ListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ListInvoicesResponse>> AsyncListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ListInvoicesResponse>>(AsyncListInvoicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ListInvoicesResponse>> PrepareAsyncListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ListInvoicesResponse>>(PrepareAsyncListInvoicesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices* request, ::TestApiGrpc::Protos::models::ServiceStatus* response, std::function<void(::grpc::Status)>) override;
      void CreateInvoices(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices* request, ::TestApiGrpc::Protos::models::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response, std::function<void(::grpc::Status)>) override;
      void ListInvoices(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ServiceStatus>* AsyncCreateInvoicesRaw(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ServiceStatus>* PrepareAsyncCreateInvoicesRaw(::grpc::ClientContext* context, const ::TestApiGrpc::Protos::models::Invoices& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ListInvoicesResponse>* AsyncListInvoicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TestApiGrpc::Protos::models::ListInvoicesResponse>* PrepareAsyncListInvoicesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateInvoices_;
    const ::grpc::internal::RpcMethod rpcmethod_ListInvoices_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateInvoices(::grpc::ServerContext* context, const ::TestApiGrpc::Protos::models::Invoices* request, ::TestApiGrpc::Protos::models::ServiceStatus* response);
    virtual ::grpc::Status ListInvoices(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateInvoices() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoices(::grpc::ServerContext* /*context*/, const ::TestApiGrpc::Protos::models::Invoices* /*request*/, ::TestApiGrpc::Protos::models::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateInvoices(::grpc::ServerContext* context, ::TestApiGrpc::Protos::models::Invoices* request, ::grpc::ServerAsyncResponseWriter< ::TestApiGrpc::Protos::models::ServiceStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListInvoices() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::TestApiGrpc::Protos::models::ListInvoicesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoices(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::TestApiGrpc::Protos::models::ListInvoicesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateInvoices<WithAsyncMethod_ListInvoices<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateInvoices() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::TestApiGrpc::Protos::models::Invoices, ::TestApiGrpc::Protos::models::ServiceStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TestApiGrpc::Protos::models::Invoices* request, ::TestApiGrpc::Protos::models::ServiceStatus* response) { return this->CreateInvoices(context, request, response); }));}
    void SetMessageAllocatorFor_CreateInvoices(
        ::grpc::MessageAllocator< ::TestApiGrpc::Protos::models::Invoices, ::TestApiGrpc::Protos::models::ServiceStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TestApiGrpc::Protos::models::Invoices, ::TestApiGrpc::Protos::models::ServiceStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoices(::grpc::ServerContext* /*context*/, const ::TestApiGrpc::Protos::models::Invoices* /*request*/, ::TestApiGrpc::Protos::models::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateInvoices(
      ::grpc::CallbackServerContext* /*context*/, const ::TestApiGrpc::Protos::models::Invoices* /*request*/, ::TestApiGrpc::Protos::models::ServiceStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListInvoices() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::TestApiGrpc::Protos::models::ListInvoicesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::TestApiGrpc::Protos::models::ListInvoicesResponse* response) { return this->ListInvoices(context, request, response); }));}
    void SetMessageAllocatorFor_ListInvoices(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::TestApiGrpc::Protos::models::ListInvoicesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::TestApiGrpc::Protos::models::ListInvoicesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::TestApiGrpc::Protos::models::ListInvoicesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoices(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::TestApiGrpc::Protos::models::ListInvoicesResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateInvoices<WithCallbackMethod_ListInvoices<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateInvoices() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoices(::grpc::ServerContext* /*context*/, const ::TestApiGrpc::Protos::models::Invoices* /*request*/, ::TestApiGrpc::Protos::models::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListInvoices() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::TestApiGrpc::Protos::models::ListInvoicesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateInvoices() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoices(::grpc::ServerContext* /*context*/, const ::TestApiGrpc::Protos::models::Invoices* /*request*/, ::TestApiGrpc::Protos::models::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateInvoices(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListInvoices() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::TestApiGrpc::Protos::models::ListInvoicesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoices(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateInvoices() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateInvoices(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoices(::grpc::ServerContext* /*context*/, const ::TestApiGrpc::Protos::models::Invoices* /*request*/, ::TestApiGrpc::Protos::models::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateInvoices(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListInvoices() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListInvoices(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::TestApiGrpc::Protos::models::ListInvoicesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoices(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateInvoices() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::TestApiGrpc::Protos::models::Invoices, ::TestApiGrpc::Protos::models::ServiceStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::TestApiGrpc::Protos::models::Invoices, ::TestApiGrpc::Protos::models::ServiceStatus>* streamer) {
                       return this->StreamedCreateInvoices(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateInvoices(::grpc::ServerContext* /*context*/, const ::TestApiGrpc::Protos::models::Invoices* /*request*/, ::TestApiGrpc::Protos::models::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateInvoices(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TestApiGrpc::Protos::models::Invoices,::TestApiGrpc::Protos::models::ServiceStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListInvoices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListInvoices() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::TestApiGrpc::Protos::models::ListInvoicesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::TestApiGrpc::Protos::models::ListInvoicesResponse>* streamer) {
                       return this->StreamedListInvoices(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListInvoices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListInvoices(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::TestApiGrpc::Protos::models::ListInvoicesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListInvoices(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::TestApiGrpc::Protos::models::ListInvoicesResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateInvoices<WithStreamedUnaryMethod_ListInvoices<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateInvoices<WithStreamedUnaryMethod_ListInvoices<Service > > StreamedService;
};

}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc


#endif  // GRPC_model_5fservices_2fInvoicesService_2eproto__INCLUDED
