// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model_services/ProductsService.proto

#include "model_services/ProductsService.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace TestApiGrpc {
namespace Protos {
namespace models {
PROTOBUF_CONSTEXPR ListProductsResponse::ListProductsResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.product_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ListProductsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListProductsResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListProductsResponseDefaultTypeInternal() {}
  union {
    ListProductsResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListProductsResponseDefaultTypeInternal _ListProductsResponse_default_instance_;
}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc
static ::_pb::Metadata file_level_metadata_model_5fservices_2fProductsService_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_model_5fservices_2fProductsService_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_model_5fservices_2fProductsService_2eproto = nullptr;

const uint32_t TableStruct_model_5fservices_2fProductsService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::ListProductsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TestApiGrpc::Protos::models::ListProductsResponse, _impl_.product_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::TestApiGrpc::Protos::models::ListProductsResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::TestApiGrpc::Protos::models::_ListProductsResponse_default_instance_._instance,
};

const char descriptor_table_protodef_model_5fservices_2fProductsService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n$model_services/ProductsService.proto\022\031"
  "TestApiGrpc.Protos.models\032\025models/Produc"
  "ts.proto\032\032models/ServiceStatus.proto\032\033go"
  "ogle/protobuf/empty.proto\"K\n\024ListProduct"
  "sResponse\0223\n\007product\030\001 \003(\0132\".TestApiGrpc"
  ".Protos.models.Product2\316\001\n\017ProductsServi"
  "ce\022`\n\016CreateProducts\022\".TestApiGrpc.Proto"
  "s.models.Product\032(.TestApiGrpc.Protos.mo"
  "dels.ServiceStatus\"\000\022Y\n\014ListProducts\022\026.g"
  "oogle.protobuf.Empty\032/.TestApiGrpc.Proto"
  "s.models.ListProductsResponse\"\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_model_5fservices_2fProductsService_2eproto_deps[3] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_models_2fProducts_2eproto,
  &::descriptor_table_models_2fServiceStatus_2eproto,
};
static ::_pbi::once_flag descriptor_table_model_5fservices_2fProductsService_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_model_5fservices_2fProductsService_2eproto = {
    false, false, 439, descriptor_table_protodef_model_5fservices_2fProductsService_2eproto,
    "model_services/ProductsService.proto",
    &descriptor_table_model_5fservices_2fProductsService_2eproto_once, descriptor_table_model_5fservices_2fProductsService_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_model_5fservices_2fProductsService_2eproto::offsets,
    file_level_metadata_model_5fservices_2fProductsService_2eproto, file_level_enum_descriptors_model_5fservices_2fProductsService_2eproto,
    file_level_service_descriptors_model_5fservices_2fProductsService_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_model_5fservices_2fProductsService_2eproto_getter() {
  return &descriptor_table_model_5fservices_2fProductsService_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_model_5fservices_2fProductsService_2eproto(&descriptor_table_model_5fservices_2fProductsService_2eproto);
namespace TestApiGrpc {
namespace Protos {
namespace models {

// ===================================================================

class ListProductsResponse::_Internal {
 public:
};

void ListProductsResponse::clear_product() {
  _impl_.product_.Clear();
}
ListProductsResponse::ListProductsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TestApiGrpc.Protos.models.ListProductsResponse)
}
ListProductsResponse::ListProductsResponse(const ListProductsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ListProductsResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.product_){from._impl_.product_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:TestApiGrpc.Protos.models.ListProductsResponse)
}

inline void ListProductsResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.product_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ListProductsResponse::~ListProductsResponse() {
  // @@protoc_insertion_point(destructor:TestApiGrpc.Protos.models.ListProductsResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ListProductsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.product_.~RepeatedPtrField();
}

void ListProductsResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ListProductsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:TestApiGrpc.Protos.models.ListProductsResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.product_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ListProductsResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .TestApiGrpc.Protos.models.Product product = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_product(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ListProductsResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TestApiGrpc.Protos.models.ListProductsResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .TestApiGrpc.Protos.models.Product product = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_product_size()); i < n; i++) {
    const auto& repfield = this->_internal_product(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TestApiGrpc.Protos.models.ListProductsResponse)
  return target;
}

size_t ListProductsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TestApiGrpc.Protos.models.ListProductsResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TestApiGrpc.Protos.models.Product product = 1;
  total_size += 1UL * this->_internal_product_size();
  for (const auto& msg : this->_impl_.product_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ListProductsResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ListProductsResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ListProductsResponse::GetClassData() const { return &_class_data_; }


void ListProductsResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ListProductsResponse*>(&to_msg);
  auto& from = static_cast<const ListProductsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestApiGrpc.Protos.models.ListProductsResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.product_.MergeFrom(from._impl_.product_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ListProductsResponse::CopyFrom(const ListProductsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestApiGrpc.Protos.models.ListProductsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListProductsResponse::IsInitialized() const {
  return true;
}

void ListProductsResponse::InternalSwap(ListProductsResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.product_.InternalSwap(&other->_impl_.product_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ListProductsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_model_5fservices_2fProductsService_2eproto_getter, &descriptor_table_model_5fservices_2fProductsService_2eproto_once,
      file_level_metadata_model_5fservices_2fProductsService_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace models
}  // namespace Protos
}  // namespace TestApiGrpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TestApiGrpc::Protos::models::ListProductsResponse*
Arena::CreateMaybeMessage< ::TestApiGrpc::Protos::models::ListProductsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TestApiGrpc::Protos::models::ListProductsResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
