// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client_Product.proto

#include "Client_Product.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Product::Product(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.product_details_)*/{}
  , /*decltype(_impl_.type_id_product_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.name_of_product_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.price_of_product_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProductDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProductDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProductDefaultTypeInternal() {}
  union {
    Product _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProductDefaultTypeInternal _Product_default_instance_;
PROTOBUF_CONSTEXPR ProductId::ProductId(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.product_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProductIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProductIdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProductIdDefaultTypeInternal() {}
  union {
    ProductId _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProductIdDefaultTypeInternal _ProductId_default_instance_;
static ::_pb::Metadata file_level_metadata_Client_5fProduct_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Client_5fProduct_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Client_5fProduct_2eproto = nullptr;

const uint32_t TableStruct_Client_5fProduct_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Product, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Product, _impl_.type_id_product_),
  PROTOBUF_FIELD_OFFSET(::Product, _impl_.name_of_product_),
  PROTOBUF_FIELD_OFFSET(::Product, _impl_.price_of_product_),
  PROTOBUF_FIELD_OFFSET(::Product, _impl_.product_details_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProductId, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProductId, _impl_.product_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Product)},
  { 10, -1, -1, sizeof(::ProductId)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Product_default_instance_._instance,
  &::_ProductId_default_instance_._instance,
};

const char descriptor_table_protodef_Client_5fProduct_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024Client_Product.proto\"n\n\007Product\022\027\n\017typ"
  "e_id_product\030\001 \001(\t\022\027\n\017name_of_product\030\002 "
  "\001(\t\022\030\n\020price_of_product\030\003 \001(\005\022\027\n\017product"
  "_details\030\004 \003(\t\"\037\n\tProductId\022\022\n\nproduct_i"
  "d\030\001 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Client_5fProduct_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Client_5fProduct_2eproto = {
    false, false, 175, descriptor_table_protodef_Client_5fProduct_2eproto,
    "Client_Product.proto",
    &descriptor_table_Client_5fProduct_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_Client_5fProduct_2eproto::offsets,
    file_level_metadata_Client_5fProduct_2eproto, file_level_enum_descriptors_Client_5fProduct_2eproto,
    file_level_service_descriptors_Client_5fProduct_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Client_5fProduct_2eproto_getter() {
  return &descriptor_table_Client_5fProduct_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Client_5fProduct_2eproto(&descriptor_table_Client_5fProduct_2eproto);

// ===================================================================

class Product::_Internal {
 public:
};

Product::Product(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Product)
}
Product::Product(const Product& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Product* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.product_details_){from._impl_.product_details_}
    , decltype(_impl_.type_id_product_){}
    , decltype(_impl_.name_of_product_){}
    , decltype(_impl_.price_of_product_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_id_product_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_id_product_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type_id_product().empty()) {
    _this->_impl_.type_id_product_.Set(from._internal_type_id_product(), 
      _this->GetArenaForAllocation());
  }
  _impl_.name_of_product_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_of_product_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name_of_product().empty()) {
    _this->_impl_.name_of_product_.Set(from._internal_name_of_product(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.price_of_product_ = from._impl_.price_of_product_;
  // @@protoc_insertion_point(copy_constructor:Product)
}

inline void Product::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.product_details_){arena}
    , decltype(_impl_.type_id_product_){}
    , decltype(_impl_.name_of_product_){}
    , decltype(_impl_.price_of_product_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_id_product_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_id_product_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_of_product_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_of_product_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Product::~Product() {
  // @@protoc_insertion_point(destructor:Product)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Product::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.product_details_.~RepeatedPtrField();
  _impl_.type_id_product_.Destroy();
  _impl_.name_of_product_.Destroy();
}

void Product::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Product::Clear() {
// @@protoc_insertion_point(message_clear_start:Product)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.product_details_.Clear();
  _impl_.type_id_product_.ClearToEmpty();
  _impl_.name_of_product_.ClearToEmpty();
  _impl_.price_of_product_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Product::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type_id_product = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type_id_product();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Product.type_id_product"));
        } else
          goto handle_unusual;
        continue;
      // string name_of_product = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name_of_product();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Product.name_of_product"));
        } else
          goto handle_unusual;
        continue;
      // int32 price_of_product = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.price_of_product_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string product_details = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_product_details();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "Product.product_details"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Product::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Product)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type_id_product = 1;
  if (!this->_internal_type_id_product().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type_id_product().data(), static_cast<int>(this->_internal_type_id_product().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Product.type_id_product");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_type_id_product(), target);
  }

  // string name_of_product = 2;
  if (!this->_internal_name_of_product().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name_of_product().data(), static_cast<int>(this->_internal_name_of_product().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Product.name_of_product");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name_of_product(), target);
  }

  // int32 price_of_product = 3;
  if (this->_internal_price_of_product() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_price_of_product(), target);
  }

  // repeated string product_details = 4;
  for (int i = 0, n = this->_internal_product_details_size(); i < n; i++) {
    const auto& s = this->_internal_product_details(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Product.product_details");
    target = stream->WriteString(4, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Product)
  return target;
}

size_t Product::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Product)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string product_details = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.product_details_.size());
  for (int i = 0, n = _impl_.product_details_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.product_details_.Get(i));
  }

  // string type_id_product = 1;
  if (!this->_internal_type_id_product().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type_id_product());
  }

  // string name_of_product = 2;
  if (!this->_internal_name_of_product().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name_of_product());
  }

  // int32 price_of_product = 3;
  if (this->_internal_price_of_product() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_price_of_product());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Product::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Product::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Product::GetClassData() const { return &_class_data_; }


void Product::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Product*>(&to_msg);
  auto& from = static_cast<const Product&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Product)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.product_details_.MergeFrom(from._impl_.product_details_);
  if (!from._internal_type_id_product().empty()) {
    _this->_internal_set_type_id_product(from._internal_type_id_product());
  }
  if (!from._internal_name_of_product().empty()) {
    _this->_internal_set_name_of_product(from._internal_name_of_product());
  }
  if (from._internal_price_of_product() != 0) {
    _this->_internal_set_price_of_product(from._internal_price_of_product());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Product::CopyFrom(const Product& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Product)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Product::IsInitialized() const {
  return true;
}

void Product::InternalSwap(Product* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.product_details_.InternalSwap(&other->_impl_.product_details_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_id_product_, lhs_arena,
      &other->_impl_.type_id_product_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_of_product_, lhs_arena,
      &other->_impl_.name_of_product_, rhs_arena
  );
  swap(_impl_.price_of_product_, other->_impl_.price_of_product_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Product::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Client_5fProduct_2eproto_getter, &descriptor_table_Client_5fProduct_2eproto_once,
      file_level_metadata_Client_5fProduct_2eproto[0]);
}

// ===================================================================

class ProductId::_Internal {
 public:
};

ProductId::ProductId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ProductId)
}
ProductId::ProductId(const ProductId& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProductId* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.product_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.product_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.product_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_product_id().empty()) {
    _this->_impl_.product_id_.Set(from._internal_product_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ProductId)
}

inline void ProductId::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.product_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.product_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.product_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ProductId::~ProductId() {
  // @@protoc_insertion_point(destructor:ProductId)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProductId::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.product_id_.Destroy();
}

void ProductId::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProductId::Clear() {
// @@protoc_insertion_point(message_clear_start:ProductId)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.product_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProductId::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string product_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_product_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProductId.product_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProductId::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProductId)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string product_id = 1;
  if (!this->_internal_product_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_product_id().data(), static_cast<int>(this->_internal_product_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProductId.product_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_product_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProductId)
  return target;
}

size_t ProductId::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProductId)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string product_id = 1;
  if (!this->_internal_product_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_product_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProductId::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProductId::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProductId::GetClassData() const { return &_class_data_; }


void ProductId::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProductId*>(&to_msg);
  auto& from = static_cast<const ProductId&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProductId)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_product_id().empty()) {
    _this->_internal_set_product_id(from._internal_product_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProductId::CopyFrom(const ProductId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProductId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProductId::IsInitialized() const {
  return true;
}

void ProductId::InternalSwap(ProductId* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.product_id_, lhs_arena,
      &other->_impl_.product_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ProductId::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Client_5fProduct_2eproto_getter, &descriptor_table_Client_5fProduct_2eproto_once,
      file_level_metadata_Client_5fProduct_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Product*
Arena::CreateMaybeMessage< ::Product >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Product >(arena);
}
template<> PROTOBUF_NOINLINE ::ProductId*
Arena::CreateMaybeMessage< ::ProductId >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProductId >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
