// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Client_Register.proto

#include "Client_Register.pb.h"
#include "Client_Register.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>

